#!/bin/bash

write_comment_block()
{
	cat >> $output_file << EOL
    Problem: $number

    Title: $title

    Description:
$description

    Url: $page_url
EOL
}

write_code()
{
	echo /\* > $output_file
	write_comment_block
	echo \*/ >> $output_file

	cat >> $output_file << EOL

namespace csharp.Level${level}
{
    public class Solution${padded_number} : SolutionBase
    {
        public override object Answer()
        {
			return 0;
        }
    }
}

EOL
}

exit_script()
{
	if [ "$dont_add_to_project" != true ]; then
		file_in_project=`sed -e 's/ xmlns.*=".*"//g' csharp.csproj | xmlstarlet sel -t -c 'count(/Project/ItemGroup/Compile[@Include="Solution'${padded_number}.cs'"])'`
		if [ "${file_in_project:0:1}" = "0" ]; then
			xmlstarlet ed -L -N x="http://schemas.microsoft.com/developer/msbuild/2003" \
			-s '/x:Project/x:ItemGroup/x:Compile[@Include]/..' -t elem -n "CompileTMP" -v "" \
			-i "//CompileTMP" -t attr -n "Include" -v "Level$level\Solution${padded_number}.cs" \
			-r "//CompileTMP" -v "Compile" \
			csharp.csproj
		fi
	fi

	if [ "$open_editor" = true ]; then
		nano $output_file
	fi
	exit 0
}

while getopts "n:rde" opt; do
  case $opt in
    n)
      number=$OPTARG
      ;;
    d)
      dont_add_to_project=true
      ;;
    e)
      open_editor=true
      ;;
    r)
      restart=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

padded_number=`printf "%03d" $number`
level=`expr $number - 1`
level=`expr $level / 25 + 1`
level=`printf "%02d" $level`
output_file=Level$level/Solution${padded_number}.cs

if [ -f $output_file ] && [ "$restart" != true ]; then
	exit_script
fi

page_url=`echo https://projecteuler.net/problem=$number`
page_html=`wget -q -O- $page_url | hxselect -i "div.problem_content"`
fixed_html=`echo $page_html | xmlstarlet ed -a '//*[@style]/br' -t text -n test -v '&nbsp;' | sed -e 's/<\(.*\) style[^>]*>/<\1>\&nbsp;/g' -e 's/\&amp;nbsp;/\&nbsp;/g'`
description=`echo $fixed_html | w3m -dump -T text/html | sed -r 's/^\s+/    /g' | sed -e 's/^/        /g'`
title=`echo $page_html | hxselect -i "div#content > h2" | xml2asc | w3m -dump -T text/html`

eval write_code

exit_script
