(*
    Problem: 2

    Title: Even Fibonacci numbers

    Description:
        Each new term in the Fibonacci sequence is generated by adding the
        previous two terms. By starting with 1 and 2, the first 10 terms will
        be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not
        exceed four million, find the sum of the even-valued terms.

    Url: https://projecteuler.net/problem=2
*)

namespace ProjectEulerSolutions.FSharp

type Solution002() = 
    static member Answer() =
        Seq.unfold(fun(a,b) -> Some(a+b,(b,a+b))) (0,1)
            |> Seq.takeWhile(fun x -> x<4000000)
            |> Seq.filter(fun x -> x % 2 = 0)
            |> Seq.sum
            |> sprintf "%d"

