/*
    Problem: 45

    Title: Triangular, pentagonal, and hexagonal

    Description:
        Triangle, pentagonal, and hexagonal numbers are generated by the following
        formulae:
        
        Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
        Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
        Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
        
        It can be verified that T[285] = P[165] = H[143] = 40755.
        
        Find the next triangle number that is also pentagonal and hexagonal.
        

    Url: https://projecteuler.net/problem=45
*/

using System;

namespace csharp.Level02
{
    public class Solution045 : SolutionBase
    {
        private bool IsPentagonal(long n) => Math.Abs((1 + Math.Sqrt(1 + 24*n))/6%1) < double.Epsilon;
        private long GetHexagonal(long n) => n * (2 * n - 1);

        public override object Answer()
        {
            for (long i = 144;; i++)
            {
                var hexagonalNumber = GetHexagonal(i);
                if (IsPentagonal(hexagonalNumber))
                    return hexagonalNumber;
            }
        }
    }
}

