/*
    Problem: 44

    Title: Pentagon numbers

    Description:
        Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first ten
        pentagonal numbers are:
        
            1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
        
        It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
        difference, 70 − 22 = 48, is not pentagonal.
        
        Find the pair of pentagonal numbers, P[j] and P[k], for which their sum and
        difference are pentagonal and D = |P[k] − P[j]| is minimised; what is the value
        of D?
        

    Url: https://projecteuler.net/problem=44
*/

using System;
using System.Collections.Generic;

namespace csharp.Level02
{
    public class Solution044 : SolutionBase
    {
        private bool IsPentagonal(int n) => Math.Abs(((1 + Math.Sqrt(1 + 24*n))/6)%1) < double.Epsilon;
        private int GetPentagonal(int n) => n*(3*n - 1)/2;
        public override object Answer()
        {
            var D = 0;
            var k = 2;
            var p = new List<int> { GetPentagonal(1) };
            while (D==0)
            {
                p.Add(GetPentagonal(k));
                for (int j = 1; j < k; j++)
                {
                    if (IsPentagonal(p[j-1] + p[k-1]))
                    {
                        D = p[k - 1] - p[j - 1];
                        if (IsPentagonal(D))
                            break;
                        D = 0;
                    }

                }
                k++;
            }
            return D;
        }
    }
}

